
lista = []
print(lista)
lista.append(0)
lista.append(1)
lista.append(2)
lista.append("a")
print(lista)
print(lista[1])
print(len(lista))
lista[1] = 22
lista.remove("a")
lista.append(2)
lista.remove(lista[0])
print(lista)
print(lista[-1])
lista.insert(-1,33)
print(lista)
lista.pop(3)
print(lista)